server:
  port: 8084

jwt:
  secret: fDeGuZGcPZW07KcvdBJovymMXcjygr8wOZNtvRSISMQ=
  access-token-validity: 3600000 #1시간(밀리초 단위 000추가)
  refresh-token-validity: 3600000

spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: jdbc:mysql://localhost:3306/apiboard6?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Sleep1205!

  profiles:
    active: oauth

  security:
    filter:
      order: 10

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

logging:
  level:
    org.springframework.security: DEBUG

  profiles:
    active: oauth